/**
 * Temporary Norwegian Bokmål string table. Full react-i18next externalization
 * (with `en` + a language switcher) lands in Stage 9; until then these constants
 * keep UI text out of components so the later migration is mechanical.
 */
export const t = {
  appName: 'Tabletop',
  tagline: 'Egendreven brettspillsporing',
  nav: {
    dashboard: 'Dashbord',
    collection: 'Samling',
    sessions: 'Partier',
    players: 'Spillere',
    settings: 'Innstillinger',
  },
  shelfOfShame: {
    title: 'Hylle uten spill',
    body: 'Spill som aldri er spilt. Planlegg en spillkveld?',
  },
  topbar: {
    searchCollection: 'Søk i samling…',
    logPlay: 'Logg et spill',
  },
  login: {
    title: 'Logg inn',
    subtitle: 'Velkommen tilbake til samlingen din',
    username: 'Brukernavn',
    password: 'Passord',
    submit: 'Logg inn',
    error: 'Feil brukernavn eller passord',
    loading: 'Logger inn…',
  },
  roles: {
    ADMIN: 'Admin',
    MEMBER: 'Medlem',
  },
  collection: {
    all: 'Alle',
    owned: 'EID',
    wishlist: 'ØNSKE',
    ownedFilter: 'Eid',
    wishlistFilter: 'Ønskeliste',
    newGame: 'Nytt spill',
    empty: 'Ingen spill ennå. Legg til ditt første!',
    searchPlaceholder: 'Søk i samling…',
  },
  gameForm: {
    createTitle: 'Nytt spill',
    editTitle: 'Rediger spill',
    title: 'Tittel',
    releaseYear: 'Utgivelsesår',
    players: 'Spillere',
    minPlayers: 'Min. spillere',
    maxPlayers: 'Maks spillere',
    playtime: 'Spilletid (min)',
    minPlaytime: 'Min. tid',
    maxPlaytime: 'Maks tid',
    minAge: 'Alder',
    weight: 'Kompleksitet (1–5)',
    price: 'Pris',
    status: 'Status',
    description: 'Beskrivelse',
    categories: 'Kategorier',
    save: 'Lagre',
    saving: 'Lagrer…',
    cancel: 'Avbryt',
    required: 'Tittel er påkrevd',
  },
  gameDetail: {
    back: 'Samling',
    players: 'Spillere',
    playtime: 'Spilletid',
    age: 'Alder',
    complexity: 'Kompleksitet',
    released: 'Utgitt',
    price: 'Pris',
    edit: 'Rediger',
    notFound: 'Fant ikke spillet',
  },
  expansions: {
    title: 'Utvidelser',
    add: 'Legg til',
    empty: 'Ingen utvidelser ennå.',
    usedIn: 'brukt i',
    createTitle: 'Ny utvidelse',
    editTitle: 'Rediger utvidelse',
    name: 'Tittel',
    delete: 'Slett',
    confirmDelete: 'Slette denne utvidelsen?',
  },
  dashboard: {
    gamesOwned: 'Spill eid',
    sessions: 'Partier',
    players: 'Spillere',
    collectionValue: 'Samlingsverdi',
    expansions: 'Utvidelser',
    avgPrice: 'Snittpris',
    perGame: 'kr / spill',
    household: 'husstand',
    collection: 'Samling',
    titles: 'titler',
    owned: 'Eid',
    wishlist: 'Ønskeliste',
    value: 'Verdi',
    recentlyAdded: 'Nylig lagt til',
    empty: 'Ingen data ennå. Legg til ditt første spill!',
  },
  common: {
    signOut: 'Logg ut',
    toggleTheme: 'Bytt tema',
    loading: 'Laster…',
    error: 'Noe gikk galt',
  },
} as const;
