import type { Strings } from './nb.js';

/** English (en). Mirrors the shape of `nb`; the type enforces completeness. */
export const en: Strings = {
  appName: 'Tabletop',
  tagline: 'Self-hosted board game tracker',
  nav: {
    dashboard: 'Dashboard',
    collection: 'Collection',
    sessions: 'Sessions',
    players: 'Players',
    settings: 'Settings',
  },
  shelfOfShame: {
    title: 'Shelf of shame',
    body: 'Games never played. Plan a game night?',
  },
  topbar: {
    searchCollection: 'Search collection…',
    logPlay: 'Log a play',
  },
  login: {
    title: 'Sign in',
    subtitle: 'Welcome back to your collection',
    username: 'Username',
    password: 'Password',
    submit: 'Sign in',
    error: 'Wrong username or password',
    loading: 'Signing in…',
  },
  roles: {
    ADMIN: 'Admin',
    MEMBER: 'Member',
  },
  collection: {
    all: 'All',
    owned: 'OWNED',
    wishlist: 'WISH',
    ownedFilter: 'Owned',
    wishlistFilter: 'Wishlist',
    newGame: 'New game',
    empty: 'No games yet. Add your first!',
    searchPlaceholder: 'Search collection…',
  },
  gameForm: {
    createTitle: 'New game',
    editTitle: 'Edit game',
    title: 'Title',
    releaseYear: 'Release year',
    players: 'Players',
    minPlayers: 'Min players',
    maxPlayers: 'Max players',
    playtime: 'Play time (min)',
    minPlaytime: 'Min time',
    maxPlaytime: 'Max time',
    minAge: 'Age',
    weight: 'Complexity (1–5)',
    price: 'Price',
    status: 'Status',
    description: 'Description',
    categories: 'Categories',
    save: 'Save',
    saving: 'Saving…',
    cancel: 'Cancel',
    required: 'Title is required',
  },
  gameDetail: {
    back: 'Collection',
    players: 'Players',
    playtime: 'Play time',
    age: 'Age',
    complexity: 'Complexity',
    released: 'Released',
    price: 'Price',
    edit: 'Edit',
    notFound: 'Game not found',
    playHistory: 'Play history',
    plays: 'plays',
    noPlays: 'No plays yet.',
  },
  rating: {
    yourGameRating: 'Your rating',
    avgSessionRating: 'Avg session rating',
    bgg: 'BGG',
    yourEveningRating: 'Your rating of the evening',
    overSessions: 'over {n} plays',
    notRated: 'Not rated yet',
    rate: 'Rate',
    save: 'Save',
    cancel: 'Cancel',
    ofTen: '/10',
    readOnly: 'read-only',
    eveningHint: 'Your rating of this play — independent of your game rating.',
  },
  expansions: {
    title: 'Expansions',
    add: 'Add',
    empty: 'No expansions yet.',
    usedIn: 'used in',
    createTitle: 'New expansion',
    editTitle: 'Edit expansion',
    name: 'Title',
    delete: 'Delete',
    confirmDelete: 'Delete this expansion?',
  },
  sessions: {
    title: 'Sessions',
    logPlay: 'Log a play',
    empty: 'No sessions yet. Log your first!',
    colGame: 'Game',
    colPlayers: 'Players',
    colWinner: 'Winner',
    colDuration: 'Duration',
    colLocation: 'Location',
    baseGame: 'base game',
    back: 'Sessions',
    players: 'Players & result',
    comment: 'Comment',
    won: 'WON',
    firstPlay: '1st play',
    score: 'Score',
    color: 'Color',
    result: 'Result',
    notFound: 'Session not found',
    photos: 'Photos from the night',
  },
  logPlay: {
    title: 'Log a play',
    step1: 'Game',
    step2: 'Players',
    step3: 'Details',
    searchGame: 'Search for a game…',
    expansionsUsed: 'Expansions used',
    playersResult: 'Players & result',
    addPlayer: 'Add',
    winner: 'Winner',
    score: 'Score',
    firstPlay: '1st play',
    start: 'Start',
    end: 'End',
    location: 'Location',
    noLocation: 'None',
    comment: 'Comment',
    next: 'Next',
    back: 'Back',
    cancel: 'Cancel',
    save: 'Save play',
    saving: 'Saving…',
    pickGame: 'Pick a game',
    pickPlayers: 'Pick at least one player',
    noGames: 'No games in the collection. Add one first.',
    noPeople: 'No players. Add some on the Players page.',
  },
  players: {
    countSuffix: 'players',
    withAccounts: 'with login accounts',
    add: 'Add player',
    guest: 'Guest',
    account: 'account',
    noSessions: 'No plays yet',
    plays: 'plays',
    winRate: 'win rate',
    avgScore: 'avg score',
    wins: 'wins',
    favorite: 'Favourite',
    empty: 'No players yet. Add the first one!',
    createTitle: 'New player',
    editTitle: 'Edit player',
    name: 'Name',
    delete: 'Delete',
    confirmDelete: 'Delete this player?',
  },
  dashboard: {
    gamesOwned: 'Games owned',
    sessions: 'Sessions',
    players: 'Players',
    collectionValue: 'Collection value',
    expansions: 'Expansions',
    avgPrice: 'Avg price',
    perGame: '/ game',
    household: 'household',
    collection: 'Collection',
    titles: 'titles',
    owned: 'Owned',
    wishlist: 'Wishlist',
    value: 'Value',
    recentlyAdded: 'Recently added',
    empty: 'No data yet. Add your first game!',
    sessions14d: 'Plays — last 14 days',
    sessionsSuffix: 'plays',
    mostPlayed: 'Most played',
    recentSessions: 'Recent plays',
    topPlayers: 'Top players — win share',
    won: 'won',
    noSessions: 'No plays yet.',
  },
  settings: {
    title: 'Settings',
    appearance: 'Appearance',
    theme: 'Theme',
    themeHint: 'Switch between light and dark interface',
    light: 'Light',
    dark: 'Dark',
    general: 'General',
    language: 'Language',
    languageHint: 'Interface language for this device',
    bggSync: 'BGG sync',
    enableSync: 'Enable sync',
    offByDefault: 'OFF BY DEFAULT',
    syncHint: 'Fetches rating & rank from BGG. Writes read-only fields only.',
    data: 'Data',
    exportCollection: 'Export collection',
    exportHint: 'Full backup of games, plays and ratings',
    comingSoon: 'coming soon',
  },
  language: {
    nb: 'Norsk (bokmål)',
    en: 'English',
    switcherLabel: 'Language',
  },
  common: {
    signOut: 'Sign out',
    toggleTheme: 'Toggle theme',
    loading: 'Loading…',
    error: 'Something went wrong',
  },
  pager: {
    prev: 'Previous',
    next: 'Next',
    of: 'of',
  },
};
