/** Norwegian Bokmål (nb) — the source locale. English mirrors this shape. */
export const nb = {
  appName: 'Tabletop',
  tagline: 'Egendreven brettspillsporing',
  nav: {
    dashboard: 'Dashbord',
    collection: 'Samling',
    sessions: 'Partier',
    players: 'Spillere',
    settings: 'Innstillinger',
    browseBgg: 'Utforsk BGG',
  },
  shelfOfShame: {
    title: 'Hylle uten spill',
    body: 'Spill som aldri er spilt. Planlegg en spillkveld?',
  },
  topbar: {
    searchCollection: 'Søk i samling…',
    logPlay: 'Logg et spill',
  },
  login: {
    title: 'Logg inn',
    subtitle: 'Velkommen tilbake til samlingen din',
    username: 'Brukernavn',
    password: 'Passord',
    submit: 'Logg inn',
    error: 'Feil brukernavn eller passord',
    loading: 'Logger inn…',
    setupTitle: 'Opprett administrator',
    setupSubtitle: 'Første gang – lag den første kontoen',
    confirmPassword: 'Bekreft passord',
    createAdmin: 'Opprett administrator',
    creating: 'Oppretter…',
    passwordTooShort: 'Passordet må ha minst 8 tegn',
    passwordMismatch: 'Passordene er ikke like',
    setupError: 'Kunne ikke opprette kontoen',
  },
  roles: {
    ADMIN: 'Admin',
    MEMBER: 'Medlem',
  },
  collection: {
    all: 'Alle',
    owned: 'EID',
    wishlist: 'ØNSKE',
    ownedFilter: 'Eid',
    wishlistFilter: 'Ønskeliste',
    newGame: 'Nytt spill',
    empty: 'Ingen spill ennå. Legg til ditt første!',
    searchPlaceholder: 'Søk i samling…',
    sortLabel: 'Sorter',
    sortMyRating: 'Min vurdering',
    sortBggRating: 'BGG-vurdering',
    sortBggRank: 'BGG-rangering',
    sortWeight: 'Kompleksitet',
    bggShort: 'BGG',
  },
  gameForm: {
    createTitle: 'Nytt spill',
    editTitle: 'Rediger spill',
    title: 'Tittel',
    releaseYear: 'Utgivelsesår',
    players: 'Spillere',
    minPlayers: 'Min. spillere',
    maxPlayers: 'Maks spillere',
    playtime: 'Spilletid (min)',
    minPlaytime: 'Min. tid',
    maxPlaytime: 'Maks tid',
    minAge: 'Alder',
    bggId: 'BGG-ID',
    weight: 'Kompleksitet (1–5)',
    price: 'Pris',
    status: 'Status',
    description: 'Beskrivelse',
    categories: 'Kategorier',
    save: 'Lagre',
    saving: 'Lagrer…',
    cancel: 'Avbryt',
    required: 'Tittel er påkrevd',
    bggSearch: 'Søk på BoardGameGeek',
    bggSearchPlaceholder: 'Skriv spillnavn eller BGG-ID…',
    bggViewOnBgg: 'Vis på BGG',
    bggNoResults: 'Ingen treff',
    cover: 'Omslagsbilde',
    coverUrl: 'URL til omslagsbilde',
    coverUrlPlaceholder: 'Lim inn en bilde-URL…',
    coverUpload: 'Last opp omslagsbilde',
  },
  gameDetail: {
    back: 'Samling',
    players: 'Spillere',
    playtime: 'Spilletid',
    age: 'Alder',
    complexity: 'Kompleksitet',
    released: 'Utgitt',
    price: 'Pris',
    edit: 'Rediger',
    delete: 'Slett',
    confirmDelete: 'Slette dette spillet? Dette kan ikke angres.',
    notFound: 'Fant ikke spillet',
    playHistory: 'Spillhistorikk',
    plays: 'partier',
    noPlays: 'Ingen partier ennå.',
    viewOnBgg: 'Vis på BoardGameGeek',
  },
  rating: {
    yourGameRating: 'Din vurdering',
    avgSessionRating: 'Snitt øktvurdering',
    bgg: 'BGG',
    yourEveningRating: 'Din vurdering av kvelden',
    overSessions: 'over {n} partier',
    notRated: 'Ikke vurdert ennå',
    rate: 'Vurder',
    save: 'Lagre',
    cancel: 'Avbryt',
    ofTen: '/10',
    readOnly: 'skrivebeskyttet',
    eveningHint: 'Egen vurdering av dette partiet — uavhengig av spillvurderingen din.',
  },
  expansions: {
    title: 'Utvidelser',
    add: 'Legg til',
    empty: 'Ingen utvidelser ennå.',
    usedIn: 'brukt i',
    createTitle: 'Ny utvidelse',
    editTitle: 'Rediger utvidelse',
    name: 'Tittel',
    delete: 'Slett',
    confirmDelete: 'Slette denne utvidelsen?',
  },
  sessions: {
    title: 'Partier',
    logPlay: 'Logg et parti',
    empty: 'Ingen partier ennå. Logg ditt første!',
    colGame: 'Spill',
    colPlayers: 'Spillere',
    colWinner: 'Vinner',
    colDuration: 'Varighet',
    colLocation: 'Sted',
    baseGame: 'grunnspill',
    back: 'Partier',
    players: 'Spillere & resultat',
    comment: 'Kommentar',
    won: 'VANT',
    firstPlay: '1. gang',
    score: 'Poeng',
    color: 'Farge',
    result: 'Resultat',
    notFound: 'Fant ikke partiet',
    photos: 'Bilder fra kvelden',
    playerless: 'Ingen spillere',
    playerlessWarning: 'Denne økten har ingen spillere – trolig fordi en spiller ble slettet.',
  },
  logPlay: {
    title: 'Logg et parti',
    step1: 'Spill',
    step2: 'Spillere',
    step3: 'Detaljer',
    searchGame: 'Søk etter spill…',
    expansionsUsed: 'Utvidelser brukt',
    playersResult: 'Spillere & resultat',
    addPlayer: 'Legg til',
    winner: 'Vinner',
    score: 'Poeng',
    firstPlay: '1. gang',
    start: 'Start',
    end: 'Slutt',
    location: 'Sted',
    noLocation: 'Ingen',
    comment: 'Kommentar',
    next: 'Neste',
    back: 'Tilbake',
    cancel: 'Avbryt',
    save: 'Lagre parti',
    saving: 'Lagrer…',
    pickGame: 'Velg et spill',
    pickPlayers: 'Velg minst én spiller',
    noGames: 'Ingen spill i samlingen. Legg til ett først.',
    noPeople: 'Ingen spillere. Legg til noen på Spillere-siden.',
  },
  players: {
    countSuffix: 'spillere',
    withAccounts: 'med innloggingskonto',
    add: 'Legg til spiller',
    guest: 'Gjest',
    account: 'konto',
    noSessions: 'Ingen partier ennå',
    plays: 'partier',
    winRate: 'seiersandel',
    avgScore: 'snittpoeng',
    wins: 'seire',
    favorite: 'Favoritt',
    empty: 'Ingen spillere ennå. Legg til den første!',
    createTitle: 'Ny spiller',
    editTitle: 'Rediger spiller',
    name: 'Navn',
    delete: 'Slett',
    confirmDelete: 'Slette denne spilleren?',
  },
  dashboard: {
    gamesOwned: 'Spill eid',
    sessions: 'Partier',
    players: 'Spillere',
    collectionValue: 'Samlingsverdi',
    expansions: 'Utvidelser',
    avgPrice: 'Snittpris',
    perGame: 'kr / spill',
    household: 'husstand',
    collection: 'Samling',
    titles: 'titler',
    owned: 'Eid',
    wishlist: 'Ønskeliste',
    value: 'Verdi',
    recentlyAdded: 'Nylig lagt til',
    empty: 'Ingen data ennå. Legg til ditt første spill!',
    sessions14d: 'Partier — siste 14 dager',
    sessionsSuffix: 'partier',
    mostPlayed: 'Mest spilt',
    recentSessions: 'Siste partier',
    topPlayers: 'Toppspillere — seiersandel',
    won: 'vant',
    noSessions: 'Ingen partier ennå.',
  },
  settings: {
    title: 'Innstillinger',
    appearance: 'Utseende',
    theme: 'Tema',
    themeHint: 'Bytt mellom lyst og mørkt grensesnitt',
    light: 'Lyst',
    dark: 'Mørkt',
    general: 'Generelt',
    language: 'Språk',
    languageHint: 'Grensesnittspråk for denne enheten',
    bggSync: 'BGG-synkronisering',
    enableSync: 'Aktivér synk',
    offByDefault: 'AV SOM STANDARD',
    syncHint: 'Henter rangering & rang fra BGG. Skriver kun skrivebeskyttede felt.',
    refreshCatalog: 'Oppdater katalog',
    refreshCatalogHint: 'Last ned nyeste spilldata fra BoardGameGeek',
    catalogUpdated: 'Oppdatert — {n} spill',
    catalogUpToDate: 'Allerede oppdatert',
    refreshFailed: 'Oppdatering feilet',
    data: 'Data',
    exportCollection: 'Eksporter samling',
    exportHint: 'Full sikkerhetskopi av spill, partier og vurderinger',
    comingSoon: 'kommer snart',
    users: {
      title: 'Brukere',
      addUser: 'Legg til bruker',
      username: 'Brukernavn',
      email: 'E-post',
      emailOptional: 'E-post (valgfritt)',
      password: 'Passord',
      confirmPassword: 'Bekreft passord',
      role: 'Rolle',
      locale: 'Språk',
      noEmail: '—',
      you: 'deg',
      resetPassword: 'Tilbakestill passord',
      resetPasswordTitle: 'Tilbakestill passord',
      resetPasswordHint: 'Sett et nytt passord for {name}.',
      createTitle: 'Ny bruker',
      delete: 'Slett',
      deleteTitle: 'Slett bruker',
      confirmDelete: 'Slette {name}? Dette kan ikke angres.',
      save: 'Lagre',
      saving: 'Lagrer…',
      cancel: 'Avbryt',
      create: 'Opprett',
      creating: 'Oppretter…',
      passwordTooShort: 'Passordet må ha minst 8 tegn',
      passwordMismatch: 'Passordene er ikke like',
      usernameRequired: 'Brukernavn er påkrevd',
      empty: 'Ingen brukere ennå.',
    },
    categories: {
      title: 'Kategorier',
      add: 'Legg til kategori',
      createTitle: 'Ny kategori',
      name: 'Navn',
      nameRequired: 'Navn er påkrevd',
      delete: 'Slett',
      deleteTitle: 'Slett kategori',
      confirmDelete: 'Slette «{name}»? Spill beholdes, men taggen fjernes.',
      empty: 'Ingen kategorier ennå.',
      create: 'Opprett',
      creating: 'Oppretter…',
      cancel: 'Avbryt',
      saving: 'Lagrer…',
    },
    locations: {
      title: 'Steder',
      add: 'Legg til sted',
      createTitle: 'Nytt sted',
      name: 'Navn',
      address: 'Adresse',
      addressOptional: 'Adresse (valgfritt)',
      nameRequired: 'Navn er påkrevd',
      delete: 'Slett',
      deleteTitle: 'Slett sted',
      confirmDelete: 'Slette «{name}»? Partier beholdes, men mister stedet.',
      empty: 'Ingen steder ennå.',
      create: 'Opprett',
      creating: 'Oppretter…',
      cancel: 'Avbryt',
      saving: 'Lagrer…',
    },
  },
  language: {
    nb: 'Norsk (bokmål)',
    en: 'English',
    switcherLabel: 'Språk',
  },
  common: {
    signOut: 'Logg ut',
    toggleTheme: 'Bytt tema',
    loading: 'Laster…',
    error: 'Noe gikk galt',
  },
  pager: {
    prev: 'Forrige',
    next: 'Neste',
    of: 'av',
  },
  browseBgg: {
    title: 'Utforsk BoardGameGeek',
    searchPlaceholder: 'Søk i BGG-katalogen…',
    add: 'Legg til valgte',
    imported: '{{created}} lagt til, {{skipped}} hoppet over',
    empty: 'Søk for å finne spill å importere',
  },
};

export type Strings = typeof nb;
